### ISSUE TITLE
TO-DO List: First Edition

### ISSUE THREAD

**Issue by fython** [fython/TelegramVisualNovelBot#1]
- [x] Support scene with images 支持带图象的场景
- [ ] Support voice message 支持语音片段信息
- [x] Friendly Load/Save functions 友好的读档/存档功能
- [x] Auto next scene 自动下一个场景
